Update keep_alive.yml

diff --git a/.github/workflows/keep_alive.yml b/.github/workflows/keep_alive.yml
--- a/.github/workflows/keep_alive.yml
+++ b/.github/workflows/keep_alive.yml
@@ -2,7 +2,7 @@ name: Keep Render App Active
 
 on:
   schedule:
-    - cron: "*/5 * * * *"  # Runs every 5 minutes
+    - cron: "*/1 * * * *"  # Runs every 5 minutes
   workflow_dispatch:  # Allows manual triggering
 
 jobs:
@@ -11,4 +11,4 @@ jobs:
 
     steps:
       - name: Ping Render App
-        run: curl -m 10 https://assignment-frontend-dz43.onrender.com || echo "Render app ping failed"
+        run: curl -m 10 https://api.render.com/deploy/srv-cvb623trie7s739c1tog?key=S82qyJPSHIs || echo "Render app ping failed"
